### ISSUE TITLE
No thumbnails on albums with spaces

### ISSUE THREAD

**Issue by keydoff** [yonjah/piwigo-privacy#13]
Hello,

  This plugin is very useful, I am very thankful for your work.
After installing it, I found that some of the albums don't have thumbnails anymore, the common point is they contain spaces in the name of the album.
Do you know how to correct that please?

Thank you

**Comment by yonjah** [comment]
Hi @keydoff  Sorry for the late reply.

I have a lot of albums with names containing spaces and never had any issues.
Can please attach a few sample links of urls that work or doesn't work ( You can replace the domain with sample.com and any digit with the digit 1 ) see if there is any obvious difference in their format from thumbnails that due work.

Also check if you have any errors in php error log. You can set `piwigo_privacy_debug` conf  to 1 to get error thrown with the actual reason for the rejection

**Comment by keydoff** [comment]
Hello Yonjah, it's my turn to apologise for the late reply.
I added the debug in the conf and here are the results for the thumbnails that don't show : 

[22-Sep-2018 10:47:12 ] PHP Fatal error:  Uncaught Exception: Could not validate path (./_data/i/galleries/Album1/Album11/Album111/image1-sq.jpg) act
ually belong to image (5555) in /www/piwigo/plugins/piwigo_privacy/helper_funcs.inc.php:25                                                                        
Stack trace:                                                                                                                                                                
#0 /www/piwigo/plugins/piwigo_privacy/helper_funcs.inc.php(245): pwg_privacy_error('Could not valid...')                                                          
#1 /www/piwigo/plugins/piwigo_privacy/get.php(63): pwg_privacy_verify_access(5555, './_data/i/galle...')                                                          
#2 {main}                                                                                                                                                                   
  thrown in /www/piwigo/plugins/piwigo_privacy/helper_funcs.inc.php on line 25

A working link for thumbnail:
Album2/Album21/Album211/111_1234.JPG

A non working link for thumbnail:
Album1/Album11/Album 111/image1-sq.jpg

Note the space in the "Album 111" while in the exception thrown we cannot see the space.

I hope these information can help you finding a solution.

Thank you a lot for your help
Best regards

**Comment by yonjah** [comment]
How did you upload the image ? did you use ftp upload ?
Usually when you upload a file piwigo save it in the album/date_hash.ext format, but it seem like
the thumbnail url that doesn't work uses the real image name

**Comment by keydoff** [comment]
In fact, this was an upgrade from a Menalto gallery3 using the piwigo extension, so yeah the paths seems not really "standard" but they are working and available, I am wondering why get.php cannot validate them (the ones with spaces in the album names).
Please tell me if I can provide you anything more to debug it.
Thank you again

**Comment by yonjah** [comment]
We need to see the base file value for this image to better understand why it is failing.
Can you change line 245 in the helper_funcs.inc.php file (https://github.com/yonjah/piwigo_privacy/blob/master/helper_funcs.inc.php#L245) from :
```php
	return pwg_privacy_error("Could not validate path ($req_path) actually belong to image ($img_id)");
```

to 

```php
	return pwg_privacy_error("Could not validate path ($req_path) actually belong to image ($img_id)  ($base_file)");
```

And check the error log again ? 
It will also log the base_file value this time.

**Comment by keydoff** [comment]
I did the modification in the php file, and here are the results : 
[08-Oct-2018 22:03:08 Europe/Paris] PHP Fatal error:  Uncaught Exception: Could not validate path (./_data/i/galleries/Album1/Album11/Album111/image1-sq.jpg) actually belong to image (5555)  (./_data/i/galleries/Album1/Album11/Album 111/pwg_representative/image av 1) in /usr/local/www/piwigo/plugins/piwigo_privacy/helper_funcs.inc.php:25

When I disable piwigo_privacy and click on the browser "view image" i get this link : 
https://example.com/_data/i/galleries/Album1/Album11/Album%20111/image%20av%201-cu_s9999x200.jpg

I hope this can help.

Thank you again

**Comment by keydoff** [comment]
I think it may help, here is the information from the mysql : 

mysql> select * from images where name like "%image av 1%"\G
*************************** 1. row ***************************
                  id: 5555
                file: image av 1.jpg
      date_available: 1970-01-01 01:00:00
       date_creation: NULL
                name: image av 1
             comment: image av 1
              author: NULL
                 hit: 2
            filesize: 164
               width: 1280
              height: 720
                 coi: NULL
  representative_ext: NULL
date_metadata_update: 2016-03-22
        rating_score: NULL
                path: ./galleries/Album1/Album11/Album 111/image av 1.jpg
 storage_category_id: 99
               level: 2
              md5sum: NULL
            added_by: 6
            rotation: 0
            latitude: NULL
           longitude: NULL
        lastmodified: 2016-09-18 18:51:20
    download_counter: 0
1 row in set (0.00 sec)

**Comment by yonjah** [comment]
@keydoff  
can you please enable the plugin and try to go to the same URL.
The error log should now show both the url and the actual database value it is being compered to.
Also can you mention the actual URL being loaded.
This will hopefully be enough to understand why it doesn't recognize it as a valid image location

**Comment by keydoff** [comment]
I think this is what I did and posted before the mysql post, or is it something else? maybe I misunderstood, please tell me.
Thank you again

**Comment by yonjah** [comment]
If you changed the code as I mentioned it should now log both the DB value and the request value.
The data you posted from mysql should be the same but for some reason the image name is `image av 1.jpg` and not `image 1.jpg` I'm not sure if it's because the log is for a different file or if somehow it got striped somewhere along the way

**Comment by keydoff** [comment]
I don't know what else to do, this is what I did when I posted this line last week: 
[08-Oct-2018 22:03:08 Europe/Paris] PHP Fatal error: Uncaught Exception: Could not validate path (./_data/i/galleries/Album1/Album11/Album111/image1-sq.jpg) actually belong to image (5555) (./_data/i/galleries/Album1/Album11/Album 111/pwg_representative/image av 1) in /usr/local/www/piwigo/plugins/piwigo_privacy/helper_funcs.inc.php:25

Please advice and sorry if I don't understand your demand.

**Comment by yonjah** [comment]
Sorry I missed that comment.
Ok I'll try to reproduce it on my environment.

It's a bit weird cause the path it is looking for is  `image1-sq.jpg` and the database value is for `image av 1`. It seem like the `av` part is somehow striped along the way.
Also I think this path should have been caught as a derivative.

Any way I hope I'll have the time to look at it properly soon

**Comment by keydoff** [comment]
Oh no problem at all, and please tell me if I can provide you any other information that can help.
Thank you very much.

**Comment by yonjah** [comment]
Ok it was indeed the white spaces.
On regular installs piwigo wont save images by there album or file name so it is not an issue.

Just released a new version (0.2.0) that should fix this issue.
read the changes to the readme file as you'll need to enable the conf `piwigo_privacy_allow_whitespaces`

**Comment by tnovak007** [comment]
Hi!
I have the same issue. I have galleries in the folders in ".\galleries" and they contain white spaces.
Unfortunately the 0.2.0 (with piwigo_privacy_allow_whitespaces = true) did not fixed the problem.

I still got errors:
PHP Fatal error:  Uncaught Exception: Could not validate path (./_data/i/galleries/**xxxxxx**/xxx.jpg) actually belong to image (50100) (./_data/i/galleries/**xxx xxx**/pwg_representative/xxx) in F:\WEB\gallery2\plugins\piwigo_privacy\helper_funcs.inc.php:25

$req_path still has the path without the whitespace "galleries/**xxxxxx**/xxx.jpg" and $img_id "galleries/**xxx xxx**/pwg_representative" has correct path with the white space.

I know almost nothing about php, but I traced the problem (I think) to line 45 in get.php:
`$req_path = filter_input(INPUT_GET, 'file', FILTER_SANITIZE_URL);`

The FILTER_SANITIZE_URL removed the white space from the gallery path and so it didn't validate. When I changed it to FILTER_SANITIZE_SPECIAL_CHARS it seems to work correctly.

So please check your code. Surely you could correct it more elegantly than my dirty fix :-)

Thank you!

Tom

**Comment by yonjah** [comment]
@tnovak007 which version of PHP are you using ?
The thing is that your URL should never contain spaces they should all be encoded to %20 like in the URL @keydoff posted.

If you are seeing this issue with properly encoded URLs I'll need a bit more info to try and track it down (like the URL your accessing and the log with more information about the actual paths being accessed to recreate locally)

**Comment by tnovak007** [comment]
Re: [yonjah/piwigo_privacy] No thumbnails on albums with spaces (#13)


Hi,

thank you for your reply.

This is my setup:
??    Piwigo 2.9.4??    OS: WINNT??    PHP: 7.2.11   MySQL: 5.7.23-log ??    ImageMagick 7.0.8-12

And this is full logs and URLS:??

/plugins/piwigo_privacy/get.php?img_id=48568&file=_data/i/galleries/Hrsufr%20pwg/zombananasaur-anger-th.jpg


[21-Oct-2018 22:24:46 Europe/Prague] PHP Fatal error:  Uncaught Exception: Could not validate path (./_data/i/galleries/Hrsufrpwg/zombananasaur-anger-th.jpg) actually belong to image (48568) (./_data/i/galleries/Hrsufr pwg/pwg_representative/zombananasaur-anger) in F:\WEB\gallery2\plugins\piwigo_privacy\helper_funcs.inc.php:25
Stack trace:
#0 F:\WEB\gallery2\plugins\piwigo_privacy\helper_funcs.inc.php(245): pwg_privacy_error('Could not valid...')
#1 F:\WEB\gallery2\plugins\piwigo_privacy\get.php(63): pwg_privacy_verify_access(48568, './_data/i/galle...')
#2 {main}
  thrown in F:\WEB\gallery2\plugins\piwigo_privacy\helper_funcs.inc.php on line 25



/plugins/piwigo_privacy/get.php?img_id=57320&file=_data/i/galleries/U.N.A.%20Frontiers%20pwg/Chapter_10/una1035-th.jpg

[21-Oct-2018 22:24:46 Europe/Prague] PHP Fatal error:  Uncaught Exception: Could not validate path (./_data/i/galleries/U.N.A.Frontierspwg/Chapter_10/una1035-th.jpg) actually belong to image (57320) (./_data/i/galleries/U.N.A. Frontiers pwg/Chapter_10/pwg_representative/una1035) in F:\WEB\gallery2\plugins\piwigo_privacy\helper_funcs.inc.php:25
Stack trace:
#0 F:\WEB\gallery2\plugins\piwigo_privacy\helper_funcs.inc.php(245): pwg_privacy_error('Could not valid...')
#1 F:\WEB\gallery2\plugins\piwigo_privacy\get.php(63): pwg_privacy_verify_access(57320, './_data/i/galle...')
#2 {main}
  thrown in F:\WEB\gallery2\plugins\piwigo_privacy\helper_funcs.inc.php on line 25
 
 
/plugins/piwigo_privacy/get.php?img_id=55641&file=_data/i/galleries/Spirit%20pwg/sexypinkangel-spirit_stallion_of_the_cimarro-th.jpg  
 
[21-Oct-2018 22:24:46 Europe/Prague] PHP Fatal error:  Uncaught Exception: Could not validate path (./_data/i/galleries/Spiritpwg/sexypinkangel-spirit_stallion_of_the_cimarro-th.jpg) actually belong to image (55641) (./_data/i/galleries/Spirit pwg/pwg_representative/sexypinkangel-spirit_stallion_of_the_cimarro) in F:\WEB\gallery2\plugins\piwigo_privacy\helper_funcs.inc.php:25
Stack trace:
#0 F:\WEB\gallery2\plugins\piwigo_privacy\helper_funcs.inc.php(245): pwg_privacy_error('Could not valid...')
#1 F:\WEB\gallery2\plugins\piwigo_privacy\get.php(63): pwg_privacy_verify_access(55641, './_data/i/galle...')
#2 {main}
  thrown in F:\WEB\gallery2\plugins\piwigo_privacy\helper_funcs.inc.php on line 25
 
 
 
As you can see I have local galleries in folders (in these examples) ./galleries/Spirit pwg/, ./galleries/U.N.A. Frontiers, ./galleries/Hrsufr pwg, but the plugin tries to access them without the white space (Spiritpwg, U.N.A.Frontierspwg, Hrsufrpwg). But URL have %20....

I hope it will help you. If you need more info I will try to give it to you.

Thank you!

With regards

Tomáš Novák





@tnovak007 which version of PHP are you using ?
The thing is that your URL should never contain spaces they should all be encoded to %20 like in the URL @keydoff posted.
If you are seeing this issue with properly encoded URLs I'll need a bit more info to try and track it down (like the URL your accessing and the log with more information about the actual paths being accessed to recreate locally)

**Comment by yonjah** [comment]
@keydoff  @tnovak007 this should be now fixed in v1.0.0

please note I changed the path validation to be more strict than the input filter ones (which weren't really compatible for validating file paths any way)

I don't think it should affect your install (but it really depends on the file names you have from you old system). If it does check the doc for the `piwigo_privacy_allow_special_chars` config option

let me know if this solve your issue

**Comment by tnovak007** [comment]
Hi!
thank you, now it's working perfectly and I can use it with no problem!
I'm very glad you made this plugin because I was always worried about the way how Piwigo passes the thumbnail pictures (derivative) through i.php without any validation so anyone who has url to this picture could see it even as a guest (I once set an album public by mistake for a moment and Google bot crawled it and exposed the thumbs in image search and these thumb links stayed accessible for anyone even after I set it private again. This plugin solved it :-)

**Comment by keydoff** [comment]
@yonjah Thank you a million, it's working now, finally I can use piwigo normally like I used to do with menalto gallery.
I had to add both parameters (white spaces and special chars), is there any risk doing that? as it's not activated by default.
Thank you again for the great job.

**Comment by yonjah** [comment]
@keydoff No Worries.
The main reason both are disabled by default is because Piwigo doesn't use them as file names. So they are not necessary for most installs.
Allowing special chars and spaces if not escaped properly might introduce shell commands injections (which are quite common with image processing) But as mentioned in the readme I don't know or think there is any vulnerabile code in this plugin or in piwigo.
This plugin only uses user input to verify the user actually asking for the correct image and for all internal commands the path saved in the DB path value is used, so the risk should be minimal.
